### ISSUE TITLE
Autolaunch TUI upon exit from Pytest run when --fold option is selected

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/pytest-fold#14]

**Comment by jeffwright13** [comment]
Suggestion in pytest-dev community is to try the `pytest_sessionfinish` hook.

Initial code (in `plugin.py`):
```
@pytest.hookimpl(trylast=True)
def pytest_sessionfinish(session: Session):
    subprocess.run(
        ["python", "/Users/jwr003/coding/pytest-fold/pytest_fold/tui.py"]
    )
```




Failure:
```
                                    File "/Users/jwr003/coding/pytest-fold/pytest_fold/tui.py", line 187, in <module>
                                                                                                                         main()
                                                                                                                                 File "/Users/jwr003/coding/pytest-fold/pytest_fold/tui.py", line 180, in main
                              Screen.wrapper(demo, catch_interrupt=True, arguments=[last_scene])
                                                                                                  File "/Users/jwr003/coding/pytest-fold/venv/lib/python3.9/site-packages/asciimatics/screen.py", line 1386, in wrapper
                                       screen = Screen.open(height,
                                                                     File "/Users/jwr003/coding/pytest-fold/venv/lib/python3.9/site-packages/asciimatics/screen.py", line 1355, in open
       screen = _CursesScreen(stdscr, height,
                                               File "/Users/jwr003/coding/pytest-fold/venv/lib/python3.9/site-packages/asciimatics/screen.py", line 2354, in __init__
                                                                                                                                                                         tbs = termios.tcgetattr(sys.stdin)[6][termios.VERASE]
                                          termios.error: (19, 'Operation not supported by device')
```

**Comment by jeffwright13** [comment]
```
Traceback (most recent call last): File "/Users/jwr003/coding/pytest-fold/pytest_fold/tui.py", line 187, in <module> main() File "/Users/jwr003/coding/pytest-fold/pytest_fold/tui.py", line 180, in main Screen.wrapper(demo, catch_interrupt=True, arguments=[last_scene]) File "/Users/jwr003/coding/pytest-fold/venv/lib/python3.9/site-packages/asciimatics/screen.py", line 1386, in wrapper screen = Screen.open(height, File "/Users/jwr003/coding/pytest-fold/venv/lib/python3.9/site-packages/asciimatics/screen.py", line 1355, in open screen = _CursesScreen(stdscr, height, File "/Users/jwr003/coding/pytest-fold/venv/lib/python3.9/site-packages/asciimatics/screen.py", line 2354, in __init__ tbs = termios.tcgetattr(sys.stdin)[6][termios.VERASE] termios.error: (19, 'Operation not supported by device') %
```

**Comment by jeffwright13** [comment]
Trouble is in asciimatics, because when I replace the launched code with
```
@pytest.hookimpl(trylast=True)
def pytest_sessionfinish(session: Session):
    subprocess.run(
        # ["python", "/Users/jwr003/coding/pytest-fold/pytest_fold/tui.py"]
        ["python", "/Users/jwr003/coding/pytest-fold/test.py"]
    )
```
 
- it runs:
 
```
============================================ test session starts ============================================
platform darwin -- Python 3.9.5, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/jwr003/coding/pytest-fold/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/jwr003/coding/pytest-fold
plugins: fold-0.5.0
collected 4 items                                                                                           

tests/test_pytest_fold.py::test_version FAILED                                                        [ 25%]
tests/test_pytest_fold.py::test_which_fails_1 FAILED                                                  [ 50%]
tests/test_pytest_fold.py::test_which_passes_1 PASSED                                                 [ 75%]
tests/test_pytest_fold.py::test_which_fails_2 FAILED                                                  [100%]Hello, worold!


================================================= FAILURES ==================================================
_______________________________________________ test_version ________________________________________________

    def test_version():
>       assert __version__ == "0.1.0"
E       AssertionError: assert '0.5.0' == '0.1.0'
E         - 0.1.0
E         ?   ^
E         + 0.5.0
E         ?   ^

tests/test_pytest_fold.py:14: AssertionError
____________________________________________ test_which_fails_1 _____________________________________________

    def test_which_fails_1():
>       assert 0
E       assert 0

tests/test_pytest_fold.py:18: AssertionError
____________________________________________ test_which_fails_2 _____________________________________________

    def test_which_fails_2():
>       assert 0
E       assert 0

tests/test_pytest_fold.py:26: AssertionError
========================================== short test summary info ==========================================
FAILED tests/test_pytest_fold.py::test_version - AssertionError: assert '0.5.0' == '0.1.0'
FAILED tests/test_pytest_fold.py::test_which_fails_1 - assert 0
FAILED tests/test_pytest_fold.py::test_which_fails_2 - assert 0
======================================== 3 failed, 1 passed in 1.92s ========================================
```
