### ISSUE TITLE
Installing package in edit mode via pip fails:

### ISSUE THREAD

**Issue by JnyJny** [jeffwright13/pytest-fold#16]
Following the directions in the README, the install of the package in editable mode in a virtual environment fails:
```
$ python3 -m pip install -e .
Obtaining file:///Users/ejo/local/pytest-fold
    ERROR: Command errored out with exit status 1:
     command: /Users/ejo/local/pytest-fold/.venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/ejo/local/pytest-fold/setup.py'"'"'; __file__='"'"'/Users/ejo/local/pytest-fold/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/t3/qswkhzj96mjb0_1j12z4q75m0000gp/T/pip-pip-egg-info-musoye0r
         cwd: /Users/ejo/local/pytest-fold/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/ejo/local/pytest-fold/setup.py", line 22, in <module>
        long_description=read("README.rst"),
      File "/Users/ejo/local/pytest-fold/setup.py", line 11, in read
        return codecs.open(file_path, encoding="utf-8").read()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/ejo/local/pytest-fold/README.rst'
    ----------------------------------------
WARNING: Discarding file:///Users/ejo/local/pytest-fold. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Looking at `setup.py`, the long description is set to `README.rst` which in fact does not exist in the package.

**Comment by jeffwright13** [comment]
Ah, yes - I changed .rst to .md recently in order to get that 733t movie to play when people visit the site :-)

**Comment by jeffwright13** [comment]
Merge completed. I'll close this.
