### ISSUE TITLE
INTERNAL ERROR thrown when --fold and --tb=native are used together

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/pytest-fold#6]
```$ pytest  --no-header  -q --fold --tb=native
.FINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/_pytest/runner.py", line 126, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/_pytest/runner.py", line 219, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/jeff/.pyenv/versions/3.8.7/envs/pytest_fold/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/jeff/coding/pytest-fold/conftest.py", line 42, in pytest_runtest_logreport
INTERNALERROR>     report.longrepr.chain[0][0].reprentries[0].lines.insert(0, "===MARKER1===")
INTERNALERROR> AttributeError: 'ReprExceptionInfo' object has no attribute 'chain'

1 failed, 1 passed in 0.09s
(pytest_fold)
~/coding/pytest-fold on  main! ⌚ 6:13:47```

**Comment by jeffwright13** [comment]
This was apparently fixed with the fix for issue 18 (required to use `-s`)
